# Generated by Django 4.2 on 2023-04-27 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('shipID', models.AutoField(primary_key=True, serialize=False)),
                ('whID', models.IntegerField(null=True)),
                ('truckID', models.IntegerField(null=True)),
                ('locationX', models.IntegerField(null=True)),
                ('locationY', models.IntegerField(null=True)),
                ('productID', models.IntegerField(null=True)),
                ('productDescription', models.CharField(max_length=255, null=True)),
                ('productCount', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=255)),
                ('userID', models.IntegerField(null=True)),
                ('upsUser', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('price', models.FloatField(default=9.99)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='amazonWeb.category')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_x', models.IntegerField(default=1)),
                ('address_y', models.IntegerField(default=1)),
                ('status', models.CharField(default='processing', max_length=50)),
                ('ups_username', models.CharField(blank=True, default='', max_length=50)),
                ('track_num', models.IntegerField(default=-1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('order_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='processing', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='amazonWeb.package')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='amazonWeb.product')),
            ],
        ),
    ]
