version: "2"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=amazontest2
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passw0rd
    ports:
      - 5433:5433
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    #command: tail -f /dev/null  # 保持容器运行
  amazon_server:
    container_name: amazon_server
    build: ./
    image: amazon_server:latest
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - 12345:12345
      - 23456:23456
      - 11111:11111
      - 22222:22222
    volumes:
      - ./:/app
    depends_on:
      - postgres
