# Generated by Django 4.1.5 on 2023-04-27 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazonAccount', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='ups_userid',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='ups_username',
        ),
    ]
